services:
  ticketassist:
    build: ./src/components/GUI-Frontend
    container_name: ticketassist
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./src/components/GUI-Frontend/data:/app/data
      - ./src/components/GUI-Frontend/.streamlit:/app/.streamlit
    env_file:
      - ./src/components/GUI-Frontend/.env
    environment:
      - OLLAMA_API_HOST=http://ollama:11434
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    networks:
      - ticketassist-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ticketassist-network

networks:
  ticketassist-network:
    driver: bridge

volumes:
  ollama-data:
    driver: local